export const actions = {
	SET_TODO_LIST: 'SET_TODO_LIST',
	SET_IS_LOADING: 'SET_IS_LOADING',
	SET_IS_DELETING: 'SET_IS_DELETING',
	SET_IS_CREATING: 'SET_IS_CREATING',
	SET_IS_UPDATING: 'SET_IS_UPDATING',
	ERROR_LOADING_TODO_DATA: 'ERROR_LOADING_TODO_DATA',
	ERROR_DELETING_TODO: 'ERROR_DELETING_TODO',
	ERROR_CREATING_TODO: 'ERROR_CREATING_TODO',
	ERROR_UPDATING_TODO: 'ERROR_UPDATING_TODO',
	SET_SELECTED_SORT: 'SET_SELECTED_SORT',
	SET_SEARCH_TERM: 'SET_SEARCH_TERM',
	SET_CREATING_TODO: 'SET_CREATING_TODO',
	SET_UPDATING_TODO: 'SET_UPDATING_TODO',
	SET_TODO_TEXT: 'SET_TODO_TEXT',
	SET_EDIT_ID: 'SET_EDIT_ID'
};
